apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-gocd-service-account
  namespace: hello-gocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-creator
  namespace: hello-gocd
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: hello-gocd
subjects:
- kind: ServiceAccount
  name: hello-gocd-service-account
roleRef:
  kind: Role
  name: deployment-creator
  apiGroup: rbac.authorization.k8s.io
