apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-creator
  namespace: gocd
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: gocd
subjects:
- kind: ServiceAccount
  name: gocd
roleRef:
  kind: Role
  name: deployment-creator
  apiGroup: rbac.authorization.k8s.io
